/**
 * Danh sách 34 đơn vị hành chính cấp tỉnh/thành phố sau cải cách 1/7/2025
 * (sáp nhập từ 63 tỉnh xuống 34, bỏ cấp huyện).
 */
export const VIETNAM_PROVINCES_2025 = [
  { id: "01", name: "Hà Nội", type: "Thành phố" },
  { id: "02", name: "Hồ Chí Minh", type: "Thành phố" },
  { id: "03", name: "Hải Phòng", type: "Thành phố" },
  { id: "04", name: "Đà Nẵng", type: "Thành phố" },
  { id: "05", name: "Cần Thơ", type: "Thành phố" },
  { id: "06", name: "Huế", type: "Thành phố" },
  { id: "07", name: "Thanh Hóa", type: "Tỉnh" },
  { id: "08", name: "Nghệ An", type: "Tỉnh" },
  { id: "09", name: "Hà Tĩnh", type: "Tỉnh" },
  { id: "10", name: "Quảng Ninh", type: "Tỉnh" },
  { id: "11", name: "Lạng Sơn", type: "Tỉnh" },
  { id: "12", name: "Cao Bằng", type: "Tỉnh" },
  { id: "13", name: "Lai Châu", type: "Tỉnh" },
  { id: "14", name: "Điện Biên", type: "Tỉnh" },
  { id: "15", name: "Sơn La", type: "Tỉnh" },
  { id: "16", name: "Tuyên Quang", type: "Tỉnh" },
  { id: "17", name: "Lào Cai", type: "Tỉnh" },
  { id: "18", name: "Thái Nguyên", type: "Tỉnh" },
  { id: "19", name: "Phú Thọ", type: "Tỉnh" },
  { id: "20", name: "Bắc Ninh", type: "Tỉnh" },
  { id: "21", name: "Hưng Yên", type: "Tỉnh" },
  { id: "22", name: "Ninh Bình", type: "Tỉnh" },
  { id: "23", name: "Quảng Trị", type: "Tỉnh" },
  { id: "24", name: "Quảng Ngãi", type: "Tỉnh" },
  { id: "25", name: "Gia Lai", type: "Tỉnh" },
  { id: "26", name: "Khánh Hòa", type: "Tỉnh" },
  { id: "27", name: "Lâm Đồng", type: "Tỉnh" },
  { id: "28", name: "Đắk Lắk", type: "Tỉnh" },
  { id: "29", name: "Đồng Nai", type: "Tỉnh" },
  { id: "30", name: "Tây Ninh", type: "Tỉnh" },
  { id: "31", name: "Vĩnh Long", type: "Tỉnh" },
  { id: "32", name: "Đồng Tháp", type: "Tỉnh" },
  { id: "33", name: "Cà Mau", type: "Tỉnh" },
  { id: "34", name: "An Giang", type: "Tỉnh" },
]
